name: "Build Windows"

on:
  push:
    branches: [ master, main ]
    tags: [ 'v*' ]
    paths-ignore:
      - 'website/**'
      - '*.md'
      - '.gitignore'
  pull_request:
    branches: [ master, main ]
    paths-ignore:
      - 'website/**'
      - '*.md'
      - '.gitignore'
  workflow_dispatch:

permissions:
  contents: write  # needed for releasing

jobs:
  # Extract version from git tag or generate from commit
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set_version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get version
        id: set_version
        run: |
          if [[ "${{ github.ref }}" == refs/tags/v* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
          else
            # Generate version from commit: YY.MM.commit-count
            DATE=$(date -u +'%y.%m')
            COUNT=$(git rev-list --count HEAD)
            VERSION="${DATE}.${COUNT}"
          fi
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "KLOGG_VERSION=${VERSION}" >> $GITHUB_ENV

  windows-x64-qt6:
    needs: version
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: windows-2022
    env:
      KLOGG_VERSION: ${{ needs.version.outputs.version }}
      KLOGG_ARCH: x64
      KLOGG_QT: Qt6
      KLOGG_QT_VERSION: 6.7.3
      KLOGG_QT_ARCH: win64_msvc2019_64
      KLOGG_QT_MODULES: qt5compat
      KLOGG_BUILD_ROOT: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v4
        with:
          path: C:\Qt
          key: windows-x64-${{ env.KLOGG_QT_VERSION }}-QtCache

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ env.KLOGG_QT_VERSION }}
          arch: ${{ env.KLOGG_QT_ARCH }}
          cached: ${{ steps.cache-qt.outputs.cache-hit }}
          modules: ${{ env.KLOGG_QT_MODULES }}
          archives: qtbase qtimageformats qtsvg qttools qttranslations icu

      - name: Cache Boost
        id: cache-boost
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}\3rdparty\boost
          key: boost-1.86.0

      - name: Install Boost
        if: steps.cache-boost.outputs.cache-hit != 'true'
        shell: bash
        run: |
          BOOST_ROOT="${{ github.workspace }}/3rdparty/boost"
          BOOST_URL="https://sourceforge.net/projects/boost/files/boost/1.86.0/boost_1_86_0.tar.bz2/download"
          mkdir -p "$BOOST_ROOT"
          curl --progress-bar --location --output "$BOOST_ROOT/download.tar.bz2" "$BOOST_URL"
          7z -o"$BOOST_ROOT" x "$BOOST_ROOT/download.tar.bz2" -y -bd
          7z -o"$BOOST_ROOT" x "$BOOST_ROOT/download.tar" -y -bd
          cd "$BOOST_ROOT" && cp -r boost_*/* .
          rm -rf boost_*/* download.tar.bz2 download.tar

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Configure
        shell: cmd
        run: |
          mkdir %KLOGG_BUILD_ROOT%
          cd %KLOGG_BUILD_ROOT%
          cmake -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCPM_SOURCE_CACHE=%GITHUB_WORKSPACE%\cpm_cache -DKLOGG_OVERRIDE_MALLOC=OFF %GITHUB_WORKSPACE%

      - name: Build
        shell: cmd
        run: |
          cmake --build %KLOGG_BUILD_ROOT% --target ci_build --config RelWithDebInfo

      - name: Prepare Release
        shell: cmd
        run: |
          packaging\windows\prepare_release.cmd

      - name: Create NSIS Installer
        uses: joncloud/makensis-action@v3.3
        with:
          script-file: packaging\windows\klogg.nsi
          arguments: "-DVERSION=%KLOGG_VERSION% -DPLATFORM=%KLOGG_ARCH% -DQT_MAJOR=%KLOGG_QT%"

      - name: Package Artifacts
        shell: cmd
        run: |
          md %KLOGG_BUILD_ROOT%\packages
          xcopy klogg-%KLOGG_VERSION%-%KLOGG_ARCH%-%KLOGG_QT%-portable.zip %KLOGG_BUILD_ROOT%\packages /y
          xcopy klogg-%KLOGG_VERSION%-%KLOGG_ARCH%-%KLOGG_QT%-pdb.zip %KLOGG_BUILD_ROOT%\packages /y
          xcopy klogg-%KLOGG_VERSION%-%KLOGG_ARCH%-%KLOGG_QT%-setup.exe %KLOGG_BUILD_ROOT%\packages /y

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: klogg-windows-x64-qt6-${{ needs.version.outputs.version }}
          path: build/packages/*
          if-no-files-found: error
          retention-days: 30

      - name: Create Release (on tag)
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/packages/klogg-${{ needs.version.outputs.version }}-x64-Qt6-portable.zip
            build/packages/klogg-${{ needs.version.outputs.version }}-x64-Qt6-pdb.zip
            build/packages/klogg-${{ needs.version.outputs.version }}-x64-Qt6-setup.exe
          draft: false
          prerelease: false
          generate_release_notes: true

  windows-x86-qt5:
    needs: version
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: windows-2022
    env:
      KLOGG_VERSION: ${{ needs.version.outputs.version }}
      KLOGG_ARCH: x86
      KLOGG_QT: Qt5
      KLOGG_QT_VERSION: 5.15.2
      KLOGG_QT_ARCH: win32_msvc2019
      KLOGG_QT_MODULES: ""
      KLOGG_BUILD_ROOT: build_x86
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v4
        with:
          path: C:\Qt
          key: windows-x86-${{ env.KLOGG_QT_VERSION }}-QtCache

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ env.KLOGG_QT_VERSION }}
          arch: ${{ env.KLOGG_QT_ARCH }}
          cached: ${{ steps.cache-qt.outputs.cache-hit }}
          modules: ${{ env.KLOGG_QT_MODULES }}
          archives: qtbase qtimageformats qtsvg qttools qttranslations

      - name: Cache Boost
        id: cache-boost
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}\3rdparty\boost
          key: boost-1.86.0

      - name: Install Boost
        if: steps.cache-boost.outputs.cache-hit != 'true'
        shell: bash
        run: |
          BOOST_ROOT="${{ github.workspace }}/3rdparty/boost"
          BOOST_URL="https://sourceforge.net/projects/boost/files/boost/1.86.0/boost_1_86_0.tar.bz2/download"
          mkdir -p "$BOOST_ROOT"
          curl --progress-bar --location --output "$BOOST_ROOT/download.tar.bz2" "$BOOST_URL"
          7z -o"$BOOST_ROOT" x "$BOOST_ROOT/download.tar.bz2" -y -bd
          7z -o"$BOOST_ROOT" x "$BOOST_ROOT/download.tar" -y -bd
          cd "$BOOST_ROOT" && cp -r boost_*/* .
          rm -rf boost_*/* download.tar.bz2 download.tar

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x86

      - name: Configure
        shell: cmd
        run: |
          mkdir %KLOGG_BUILD_ROOT%
          cd %KLOGG_BUILD_ROOT%
          cmake -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCPM_SOURCE_CACHE=%GITHUB_WORKSPACE%\cpm_cache -DKLOGG_OVERRIDE_MALLOC=OFF %GITHUB_WORKSPACE%

      - name: Build
        shell: cmd
        run: |
          cmake --build %KLOGG_BUILD_ROOT% --target ci_build --config RelWithDebInfo

      - name: Prepare Release
        shell: cmd
        run: |
          packaging\windows\prepare_release.cmd

      - name: Create NSIS Installer
        uses: joncloud/makensis-action@v3.3
        with:
          script-file: packaging\windows\klogg.nsi
          arguments: "-DVERSION=%KLOGG_VERSION% -DPLATFORM=%KLOGG_ARCH% -DQT_MAJOR=%KLOGG_QT%"

      - name: Package Artifacts
        shell: cmd
        run: |
          md %KLOGG_BUILD_ROOT%\packages
          xcopy klogg-%KLOGG_VERSION%-%KLOGG_ARCH%-%KLOGG_QT%-portable.zip %KLOGG_BUILD_ROOT%\packages /y
          xcopy klogg-%KLOGG_VERSION%-%KLOGG_ARCH%-%KLOGG_QT%-pdb.zip %KLOGG_BUILD_ROOT%\packages /y
          xcopy klogg-%KLOGG_VERSION%-%KLOGG_ARCH%-%KLOGG_QT%-setup.exe %KLOGG_BUILD_ROOT%\packages /y

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: klogg-windows-x86-qt5-${{ needs.version.outputs.version }}
          path: build_x86/packages/*
          if-no-files-found: error
          retention-days: 30

      - name: Create Release (on tag)
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build_x86/packages/klogg-${{ needs.version.outputs.version }}-x86-Qt5-portable.zip
            build_x86/packages/klogg-${{ needs.version.outputs.version }}-x86-Qt5-pdb.zip
            build_x86/packages/klogg-${{ needs.version.outputs.version }}-x86-Qt5-setup.exe
          draft: false
          prerelease: false
          generate_release_notes: true